#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
  - certbot 

runcmd:
  - apt-get update
  - apt-get install -y docker.io docker-compose
  - systemctl start docker
  - systemctl enable docker
  - |
    until docker info >/dev/null 2>&1; do
      echo "waiting for docker..."
      sleep 5
    done
  - mkdir -p /opt/tahajjud
  - cd /opt/tahajjud
  - |
    cat <<EOF > /opt/tahajjud/docker-compose.yml
    ${compose_content}
    EOF
  - |
    cat <<EOF > /opt/tahajjud/nginx.conf
    ${nginx_content}
    EOF
  - certbot certonly --standalone -d whenistahajjud.com --non-interactive --agree-tos -m you@example.com
  - docker-compose up -d
  - docker-compose restart nginx
