#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
  - certbot

write_files:
  - path: /opt/tahajjud/docker-compose.yml
    permissions: '0644'
    content: |
      ${indent(6, compose_content)}
  - path: /opt/tahajjud/nginx.conf
    permissions: '0644'
    content: |
      ${indent(6, nginx_content)}

bootcmd: 
  - apt-get update
  - apt-get install -y docker.io docker-compose
  - systemctl start docker
  - systemctl enable docker

runcmd:
  - bash -c 'until docker info >/dev/null 2>&1; do echo "waiting for docker..."; sleep 5; done'
  #- certbot certonly --standalone -d whenistahajjud.com --non-interactive --agree-tos -m you@example.com
  - until [ -f /opt/tahajjud/docker-compose.yml ]; do sleep 1; done
  - docker-compose -f /opt/tahajjud/docker-compose.yml up -d
  - docker-compose restart nginx